MODEL:
  META_ARCHITECTURE: "SparseRCNNLite"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  # Use generic ROI_HEADS keys to be compatible without project plugin
  ROI_HEADS:
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("personal_train",)
  TEST: ("personal_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0005
  STEPS: (500, 750)
  MAX_ITER: 2000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: False
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 2
VERSION: 2